In [1]:
l = range(1000)

In [2]:
import numpy as np

In [3]:
d = np.arange(1000)

In [4]:
%time for i in range(1,1000): r = [x*2 for x in l]

Wall time: 114 ms


In [5]:
%time for i in range(1,1000): r = d*2

Wall time: 8.99 ms


In [6]:
x = np.zeros((4,4))

In [7]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
y = np.ones((5,5))

In [9]:
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
z = np.empty((7,7))

In [11]:
z

array([[4.82336277e+228, 4.72098782e+164, 8.88054509e+252,
        3.17109511e+180, 7.34514289e+223, 1.27734658e-152,
        1.12038871e+219],
       [6.25151164e-085, 1.42731838e+228, 6.01346954e-154,
        5.98149672e-154, 2.58634340e+161, 3.59075320e+185,
        4.76660077e+180],
       [7.26606611e+223, 7.87265961e+276, 8.41476458e+276,
        1.39759530e-152, 9.08367206e+223, 2.45068391e+198,
        1.46914166e+195],
       [7.36101917e+223, 1.41975521e-022, 3.42972241e+161,
        2.35053988e+180, 1.27966001e-152, 1.18032841e+243,
        5.03028269e+180],
       [1.04828564e+228, 6.79316720e+247, 3.86599061e+233,
        9.00114496e+223, 1.28515403e+248, 9.15026598e+199,
        1.27967852e-152],
       [3.94655105e+180, 7.08519663e+194, 6.01346954e-154,
        3.68019409e+180, 2.93471106e-115, 1.33295183e+179,
        2.04723948e+190],
       [2.66064963e-260, 7.70858946e+218, 6.01334668e-154,
        4.47593816e-091, 7.01413727e-009, 1.67433455e+243,
        4.00247480

In [12]:
list = [1,5,9,8,7,2,6,3,4,8,5,2,3,6,9]

In [13]:
np.array(list)

array([1, 5, 9, 8, 7, 2, 6, 3, 4, 8, 5, 2, 3, 6, 9])

In [14]:
ac = np.empty((10,10))

In [15]:
ac.shape

(10, 10)

In [16]:
reshap = ac.reshape((5,5,4))

In [17]:
reshap

array([[[6.92211825e-312, 0.00000000e+000, 1.69759663e-313,
         4.94065646e-324],
        [6.92211830e-312, 5.92878775e-323, 6.92195997e-312,
         1.90979621e-313],
        [2.85250929e+256, 0.00000000e+000, 9.70158285e+189,
         0.00000000e+000],
        [2.12199579e-313, 4.00086397e+252, 6.92211830e-312,
         5.75387430e+228],
        [6.92195997e-312, 2.33419537e-313, 8.66638020e-307,
         0.00000000e+000]],

       [[1.50690022e-321, 0.00000000e+000, 2.54639495e-313,
         4.94065646e-324],
        [6.92211831e-312, 5.92878775e-323, 6.92195996e-312,
         2.75859453e-313],
        [0.00000000e+000, 0.00000000e+000, 1.50690022e-321,
         0.00000000e+000],
        [2.97079411e-313, 4.94065646e-324, 6.92211831e-312,
         5.92878775e-323],
        [6.92195997e-312, 3.18299369e-313, 0.00000000e+000,
         0.00000000e+000]],

       [[1.50690022e-321, 0.00000000e+000, 3.39519327e-313,
         4.94065646e-324],
        [6.92211821e-312, 5.92878775e-3

In [18]:
resh= ac.reshape((2,2,5,5))

In [19]:
resh

array([[[[6.92211825e-312, 0.00000000e+000, 1.69759663e-313,
          4.94065646e-324, 6.92211830e-312],
         [5.92878775e-323, 6.92195997e-312, 1.90979621e-313,
          2.85250929e+256, 0.00000000e+000],
         [9.70158285e+189, 0.00000000e+000, 2.12199579e-313,
          4.00086397e+252, 6.92211830e-312],
         [5.75387430e+228, 6.92195997e-312, 2.33419537e-313,
          8.66638020e-307, 0.00000000e+000],
         [1.50690022e-321, 0.00000000e+000, 2.54639495e-313,
          4.94065646e-324, 6.92211831e-312]],

        [[5.92878775e-323, 6.92195996e-312, 2.75859453e-313,
          0.00000000e+000, 0.00000000e+000],
         [1.50690022e-321, 0.00000000e+000, 2.97079411e-313,
          4.94065646e-324, 6.92211831e-312],
         [5.92878775e-323, 6.92195997e-312, 3.18299369e-313,
          0.00000000e+000, 0.00000000e+000],
         [1.50690022e-321, 0.00000000e+000, 3.39519327e-313,
          4.94065646e-324, 6.92211821e-312],
         [5.92878775e-323, 6.92195997e-312, 

In [20]:
resh.ndim

4

In [21]:
reshap.ndim

3

In [27]:
a = np.random.randn(10)

In [29]:
b = np.random.randn(10)

In [30]:
a

array([ 0.62767898, -0.35575834, -1.93890483,  0.58675126,  0.64540541,
        0.91908133,  2.39162559,  0.02272884,  0.23779281,  2.21357062])

In [31]:
b

array([-0.83262982,  0.53187688, -0.43486853, -0.21957827,  0.03682814,
        0.37636389,  0.9970563 ,  0.18168829,  0.47950474,  0.05756935])

In [32]:
a+b

array([-0.20495084,  0.17611854, -2.37377336,  0.36717299,  0.68223356,
        1.29544522,  3.38868189,  0.20441713,  0.71729754,  2.27113997])

In [33]:
a-b

array([ 1.4603088 , -0.88763522, -1.5040363 ,  0.80632953,  0.60857727,
        0.54271744,  1.39456929, -0.15895945, -0.24171193,  2.15600128])

In [34]:
a/2

array([ 0.31383949, -0.17787917, -0.96945242,  0.29337563,  0.32270271,
        0.45954067,  1.19581279,  0.01136442,  0.1188964 ,  1.10678531])

In [35]:
a*7

array([  4.39375285,  -2.49030841, -13.57233381,   4.10725882,
         4.51783789,   6.43356933,  16.74137913,   0.15910189,
         1.66454964,  15.49499436])

In [37]:
a[a>b]

array([0.62767898, 0.58675126, 0.64540541, 0.91908133, 2.39162559,
       2.21357062])

In [38]:
a[a<b]

array([-0.35575834, -1.93890483,  0.02272884,  0.23779281])

In [39]:
a>0

array([ True, False, False,  True,  True,  True,  True,  True,  True,
        True])

## Indexing

In [40]:
a[0]

0.6276789783365245

In [42]:
a[0:5]

array([ 0.62767898, -0.35575834, -1.93890483,  0.58675126,  0.64540541])

### Fancy Indexing

In [43]:
a[[2,6]]

array([-1.93890483,  2.39162559])

In [44]:
b[[2,6,9,4,5]]

array([-0.43486853,  0.9970563 ,  0.05756935,  0.03682814,  0.37636389])

In [45]:
b[5:8]

array([0.37636389, 0.9970563 , 0.18168829])

In [47]:
x = np.random.randn(10,10)

In [48]:
x.ndim

2

In [49]:
x.size

100

In [50]:
x

array([[ 0.36305858, -0.71807689,  0.08645407,  1.3970436 ,  0.31639186,
        -1.09776674,  1.42068682, -0.38637266,  0.28427365,  0.55261694],
       [-0.06880073,  0.31107453, -0.98373876, -1.13997054, -0.47620082,
        -1.15762074, -0.7357643 ,  0.01487895, -0.38581149,  0.24498854],
       [ 0.07494107, -0.13495276, -0.35336919,  0.19250546,  0.07911764,
         1.98981749,  3.02034747, -0.4976795 , -1.4848378 , -0.11351214],
       [ 0.39040559,  0.12241616,  1.37913576,  0.71339915, -0.07676098,
         1.47903548, -0.43930472, -2.44503028, -1.44777591,  0.86677172],
       [ 0.83831605,  1.47566931, -0.07697329,  0.34801559,  0.20887906,
         0.31788234,  0.14846482, -1.47600525,  1.48291308,  0.02894842],
       [-0.05785078, -0.37672279,  0.47165879, -1.39770371, -1.8109739 ,
        -0.10813866,  0.1395554 , -0.56430901,  1.25746325,  0.3510689 ],
       [ 0.72984398, -0.02621524,  0.59705502,  1.17219933, -0.06247257,
        -0.77636709,  0.27127019, -1.08400168

In [52]:
x[0][5]

-1.0977667437729635

In [55]:
x[:5,5]

array([-1.09776674, -1.15762074,  1.98981749,  1.47903548,  0.31788234])

In [57]:
one = np.ones((5,5))

In [58]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
one[1:4,1:4]=0

In [64]:
one

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
one[-1]

array([1., 1., 1., 1., 1.])

In [66]:
z = np.empty((2,2))

In [67]:
z

array([[0.35575834, 1.93890483],
       [0.02272884, 0.23779281]])

In [71]:
z[0:-1]

array([[0.35575834, 1.93890483]])

In [73]:
ma = np.sqrt(z)

In [74]:
ma

array([[0.59645481, 1.39244563],
       [0.15076088, 0.48764004]])

In [76]:
m = np.max(z)

In [77]:
m

1.9389048304950258

In [78]:
sqr = np.sqrt(z)

In [79]:
sqr

array([[0.59645481, 1.39244563],
       [0.15076088, 0.48764004]])

In [80]:
f = np.array([1,5,9,3,6,8])

In [81]:
g = np.array([2,3,10,1,8,4])

In [82]:
maxarra = np.maximum(f,g)

In [83]:
maxarra

array([ 2,  5, 10,  3,  8,  8])

## np.where

In [89]:
modifiyarray = np.where(g<5,len(g),f)

In [90]:
modifiyarray

array([6, 6, 9, 6, 6, 6])